DevXuongMoc/DevXuongMoc/Controllers/CustomerMemberController.cs
using DevXuongMoc.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Protocol;

namespace DevXuongMoc.Controllers
{
    public class CustomerMemberController : Controller
    {
        private readonly XuongMocContext _context;
        public CustomerMemberController(XuongMocContext context)
        {
            _context = context;
        }

        public IActionResult Index(string url)
        {
            if (HttpContext.Session.GetString("Member") != null)
            {
                var dataLogin = JsonConvert.DeserializeObject<Customer>(HttpContext.Session.GetString("Member"));
                ViewBag.Customer = dataLogin;
            }
            ViewBag.UrlAction = url;
            return View();
        }


        /// <summary>
        /// Xử lý chức năng khi người dùng click vào Register
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Register(Customer model)
        {
            try
            {
                var pass = model.Password;
                model.Password = pass;
                model.CreatedDate = DateTime.Now;
                model.UpdatedDate = DateTime.Now;
                model.Isactive = 1;
                _context.Add(model);
                _context.SaveChanges();
                return View();
            }
            catch (Exception ex)
            {
                TempData["errorRegister"] = "Lỗi đăng ký;" + ex.Message;
                return RedirectToAction("Index");
            }
        }


        [HttpPost]
        public IActionResult Login(LoginUser model, string urlAction)
        {
            var pass = model.Password;
            var data = _context.Customers.Where(x => x.Isactive == 1).Where(x => x.Username.Equals(model.UserOrEmail) || x.Email.Equals(model.UserOrEmail)).FirstOrDefault(x => x.Password.Equals(pass));
            var dataLogin = data.ToJson();
            if (data != null)
            {
                HttpContext.Session.SetString("Member", dataLogin);
                if (!string.IsNullOrEmpty(urlAction))
                {
                    return Redirect(urlAction);
                }
                return RedirectToAction("Index");
            }
            TempData["errorLogin"] = "Lỗi đăng nhập";
            return RedirectToAction("Index");
        }


    }
}

DevXuongMoc/DevXuongMoc/Views/CustomerMember/Index.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Login information";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    form{
        border: 1px solid #ccc;
        border-radius: 5px;
        background: #ccc;
        padding: 1rem;
       
    }
</style>
<div class="container" style="margin-top:100px;">
@{
    if (HttpContextAccessor.HttpContext.Session.GetString("Member") != null)
    {
        <div class="row">
            <h2 class="text-center my-2 py-2">Welcome to, @ViewBag.Customer.Name</h2>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-md-6">
                <h2 class="text-center my-2 py-2">LOGIN INFORMATION</h2>
                <form asp-action="Login" asp-controller="CustomerMember" method="post">
                    <div class="mb-3">
                        <label for="UserOrEmail" class="form-label">Email/UserName</label>
                        <input type="text" class="form-control" id="UserOrEmail" name="UserOrEmail" placeholder="name@example.com / username" value="" />
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password" name="password" value="" />
                    </div>

                    <input type="hidden" name="urlAction" value="@ViewBag.UrlAction" />
                    <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                    <span style="color:red">@TempData["errorLogin"]</span>
                </form>
            </div>
            <div class="col-md-6">
                <h2 class="text-center my-2 py-2">REGISTRATION INFORMATION</h2>
                <form asp-action="Register" asp-controller="CustomerMember" method="post">
                    <div class="mb-3">
                        <label for="Name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="Name" name="Name" placeholder="FullName....." />
                    </div>
                    <div class="mb-3">
                        <label for="USERNAME" class="form-label">UserName</label>
                        <input type="text" class="form-control" id="USERNAME" name="USERNAME" placeholder="UserName....." />
                    </div>
                    <div class="mb-3">
                        <label for="EMAIL" class="form-label">Email</label>
                        <input type="email" class="form-control" id="EMAIL" name="EMAIL" placeholder="name@example.com" />
                    </div>
                    <div class="mb-3">
                        <label for="PASSWORD" class="form-label">Password</label>
                        <input type="password" class="form-control" id="PASSWORD" name="PASSWORD" />
                    </div>
                    ​<button type="submit" class="btn btn-primary btn-block">Register</button>
                    <span style="color:red">@TempData["errorRegister"]</span>
                </form>
            </div>
        </div>
    }
}
</div>

DevXuongMoc/DevXuongMoc/Views/CustomerMember/Register.cshtml
@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h2 class="text-center my-2 py-2">
        Đăng ký thành công, đăng nhập để tiếp tục...
    </h2>
</div>